openapi: 3.0.3
info:
  description: Galerapagos Server REST API spec
  title: galerapagos-server
  version: 1.0.0
servers:
- description: Local
  url: http://localhost:3001/api/{version}
  variables:
    ServerDNS:
      default: go-hexagonal-skeletor.audibene.net
      enum:
      - go-hexagonal-skeletor.audibene.net
    version:
      default: v1
      enum:
      - v1
- description: Production
  url: https://{ServerDNS}/api/{version}
  variables:
    ServerDNS:
      default: go-hexagonal-skeletor.audibene.net
      enum:
      - go-hexagonal-skeletor.audibene.net
    version:
      default: v1
      enum:
      - v1
security:
- BearerAuth: []
paths:
  /api/v1/game:
    get:
      description: Get Many Games
      operationId: getManyGames
      parameters:
      - in: query
        name: page
        schema:
          type: integer
      - in: query
        name: pageSize
        schema:
          type: integer
      - in: query
        name: sortBy
        schema:
          type: string
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/ModelSortDirection'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPortsGetManyGamesQuery'
          description: OK
      summary: Get Many Games
      tags:
      - games
    patch:
      description: Update One Game
      operationId: updateOneGame
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiPortsUpdateGameRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPortsUpdateGameRequest'
          description: OK
      summary: Update One Game
      tags:
      - games
    post:
      description: Create One Game
      operationId: createOneGame
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiPortsCreateGameRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPortsCreateGameRequest'
          description: OK
      summary: Create One Game
      tags:
      - games
  /api/v1/game/{gid}:
    get:
      description: Get One Game
      operationId: getOneGame
      parameters:
      - in: path
        name: gid
        required: true
        schema:
          example: xxxx-xxxxx-xxxxx-xxxx
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelGame'
          description: OK
      summary: Get One Game
      tags:
      - games
  /api/v1/player:
    get:
      description: Get Many Players
      operationId: getManyPlayers
      parameters:
      - in: query
        name: page
        schema:
          type: integer
      - in: query
        name: pageSize
        schema:
          type: integer
      - in: query
        name: sortBy
        schema:
          type: string
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/ModelSortDirection'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPortsGetManyPlayersQuery'
          description: OK
      summary: Get Many Players
      tags:
      - players
    patch:
      description: Update One Player
      operationId: updateOnePlayer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiPortsUpdatePlayerRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPortsUpdatePlayerRequest'
          description: OK
      summary: Update One Player
      tags:
      - players
    post:
      description: Create One Player
      operationId: createOnePlayer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiPortsCreatePlayerRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPortsCreatePlayerRequest'
          description: OK
      summary: Create One Player
      tags:
      - players
  /api/v1/player/{gid}:
    get:
      description: Get One Player
      operationId: getOnePlayer
      parameters:
      - in: path
        name: gid
        required: true
        schema:
          example: xxxx-xxxxx-xxxxx-xxxx
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelPlayer'
          description: OK
      summary: Get One Player
      tags:
      - players
components:
  schemas:
    ApiPortsCreateGameRequest:
      properties:
        gid:
          nullable: true
          type: string
      type: object
    ApiPortsCreatePlayerRequest:
      properties:
        email:
          type: string
        familyName:
          type: string
        gid:
          nullable: true
          type: string
        givenName:
          type: string
        password:
          type: string
      type: object
    ApiPortsGetManyGamesQuery:
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        sort:
          $ref: '#/components/schemas/ModelSortDirection'
        sortBy:
          nullable: true
          type: string
      type: object
    ApiPortsGetManyPlayersQuery:
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        sort:
          $ref: '#/components/schemas/ModelSortDirection'
        sortBy:
          nullable: true
          type: string
      type: object
    ApiPortsUpdateGameRequest:
      properties:
        status:
          nullable: true
          type: string
      type: object
    ApiPortsUpdatePlayerRequest:
      properties:
        email:
          nullable: true
          type: string
        familyName:
          nullable: true
          type: string
        givenName:
          nullable: true
          type: string
        password:
          nullable: true
          type: string
      type: object
    ModelGame:
      properties:
        createdAt:
          type: string
        foodLevel:
          type: integer
        gid:
          type: string
        playerTurns:
          items:
            $ref: '#/components/schemas/ModelPlayer'
          nullable: true
          type: array
        raftLevel:
          type: integer
        status:
          type: string
        updatedAt:
          type: string
        waterLevel:
          type: integer
        weatherCards:
          items:
            $ref: '#/components/schemas/ModelWeatherCard'
          nullable: true
          type: array
        wreckCardGids:
          items:
            type: string
          nullable: true
          type: array
      type: object
    ModelPlayer:
      properties:
        createdAt:
          format: date-time
          type: string
        email:
          type: string
        familyName:
          type: string
        gid:
          type: string
        givenName:
          type: string
        password:
          type: string
        updatedAt:
          format: date-time
          type: string
      type: object
    ModelSortDirection:
      enum:
      - ASC
      - DESC
      nullable: true
      type: string
    ModelWeatherCard:
      properties:
        gid:
          type: string
        is_final_game:
          type: boolean
        name:
          type: string
        quantity:
          type: integer
        water_level:
          type: integer
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
